export { SeekerDashboard } from './Dashboard'
export { ApplicationsPage } from './ApplicationsPage'
export { InterviewsPage } from './InterviewsPage'
export { ResumePage } from './ResumePage'
export { AIAssistantPage } from './AIAssistantPage'
export { ProfilePage } from './ProfilePage'
export { NotificationsPage } from './NotificationsPage'
export { RecommendationsPage } from './RecommendationsPage'
export { SavedJobsPage } from './SavedJobsPage'
export { SettingsPage } from './SettingsPage'
export { default as ApplicationDetailsPage } from './ApplicationDetailsPage'
export { default as InterviewDetailsPage } from './InterviewDetailsPage'